"""add token approve/rejected

Revision ID: 6b225f7a7922
Revises: d9eb256ddb8d
Create Date: 2022-03-06 14:48:55.342210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b225f7a7922'
down_revision = 'd9eb256ddb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('rejected')
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
